server.port: 8080

management:
  security:
    enabled: false

oauth:
  enabled: true
  all-in-one: true

spring:
  application:
    name: security
  oauth:
    url: jdbc:mysql://mysql:3306/oauth
    username: root
    password: supersecret
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        hbm2ddl:
          auto: validate
server:
  port: 0
eureka:
  client:
    serviceUrl:
      registerWithEureka: false
      fetchRegistry: false
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true