spring:
  application:
    name: zuul-server
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul.sensitiveHeaders: Cookie,Set-Cookie